export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL'

export const SET_USER_PROFILE_REQUEST = 'SET_USER_PROFILE_REQUEST'
export const SET_USER_PROFILE_SUCCESS = 'SET_USER_PROFILE_SUCCESS'
export const SET_USER_PROFILE_FAIL = 'SET_USER_PROFILE_FAIL'

export const GET_USER_PROFILE_REQUEST = 'GET_USER_PROFILE_REQUEST'
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS'
export const GET_USER_PROFILE_FAIL = 'GET_USER_PROFILE_FAIL'

export const GET_VARIFY_CODE_REQUEST = 'GET_VARIFY_CODE_REQUEST'
export const GET_VARIFY_CODE_SUCCESS = 'GET_VARIFY_CODE_SUCCESS'
export const GET_VARIFY_CODE_FAIL = 'GET_VARIFY_CODE_FAIL'

export const VERIFY_PASSWORD_CODE_REQUEST = 'VERIFY_PASSWORD_CODE_REQUEST'
export const VERIFY_PASSWORD_CODE_SUCCESS = 'VERIFY_PASSWORD_CODE_SUCCESS'
export const VERIFY_PASSWORD_CODE_FAIL = 'VERIFY_PASSWORD_CODE_FAIL'

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST'
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS'
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL'

export const UPLOAD_AVATAR_REQUEST = 'UPLOAD_AVATAR_REQUEST'
export const UPLOAD_AVATAR_SUCCESS = 'UPLOAD_AVATAR_SUCCESS'
export const UPLOAD_AVATAR_FAIL = 'UPLOAD_AVATAR_FAIL'

export const GET_ALL_POST_REQUEST = 'GET_ALL_POST_REQUEST'
export const GET_ALL_POST_SUCCESS = 'GET_ALL_POST_SUCCESS'
export const GET_ALL_POST_FAIL = 'GET_ALL_POST_FAIL'

export const GET_POST_OF_USER_REQUEST = 'GET_POST_OF_USER_REQUEST'
export const GET_POST_OF_USER_SUCCESS = 'GET_POST_OF_USER_SUCCESS'
export const GET_POST_OF_USER_FAIL = 'GET_POST_OF_USER_FAIL'

export const GET_POST_BY_ID_REQUEST = 'GET_POST_BY_ID_REQUEST'
export const GET_POST_BY_ID_SUCCESS = 'GET_POST_BY_ID_SUCCESS'
export const GET_POST_BY_ID_FAIL = 'GET_POST_BY_ID_FAIL'

export const LIKE_POST_REQUEST = 'LIKE_POST_REQUEST'
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS'
export const LIKE_POST_FAIL = 'LIKE_POST_FAIL'

export const GET_FAVORITE_POST_REQUEST = 'GET_FAVORITE_POST_REQUEST'
export const GET_FAVORITE_POST_SUCCESS = 'GET_FAVORITE_POST_SUCCESS'
export const GET_FAVORITE_POST_FAIL = 'GET_FAVORITE_POST_FAIL'

export const GET_POSTED_POST_REQUEST = 'GET_POSTED_POST_REQUEST'
export const GET_POSTED_POST_SUCCESS = 'GET_POSTED_POST_SUCCESS'
export const GET_POSTED_POST_FAIL = 'GET_POSTED_POST_FAIL'
